config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ゲストログインルーティング
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :update] do
      resources :comments, only: [:index, :destroy]
      member do
        patch :active
      end
    end
  end

  # ユーザー側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get 'posts/search' => "posts#search"
    get 'search_tag' => "posts#search_tag"
    get 'search_title' => "posts#search_title"
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only:[:index, :show, :edit, :update] do
      resources :favorites, only: [:index]
      collection do
        get :confirm
        patch :withdrawal
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :post
  # バリデーション
  validates :comment, presence: true, length: { maximum: 70 }
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @user = User.find(params[:user_id])
    @comments = @user.comments
  end

  def destroy
    comment = Comment.find(params[:id])
    user_id = comment.user_id
    comment.destroy
    redirect_to admin_user_comments_path(user_id), notice: "コメントを削除しました"
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<!--管理者側ユーザーコメント-->
<div class="container mt-4 mb-4">
  <div class="row">
    <div class="col-12">
      <% if @comments.present? %>
        <h2><%= @user.nick_name %>のコメント一覧</h2>
        <div class="row">
          <div class="col-12">
            <table class="table mt-4">
              <thead>
                <tr>
                  <th>投稿タイトル</th>
                  <th>コメント</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              <% @comments.each do |comment| %>
                <tr>
                  <td class="align-middle"><%= comment.post.title %></td>
                  <td class="align-middle"><%= comment.comment %></td>
                  <td class="align-middle"><%= link_to "コメントを削除", admin_user_comment_path(comment, comment), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger" %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% else %>
        <h2>コメントはありません</h4>
      <% end %>
    </div>
  </div>
</div>