config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ゲストログインルーティング
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :update] do
      resources :comments, only: [:index, :destroy]
      member do
        patch :active
      end
    end
  end

  # ユーザー側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get 'posts/search' => "posts#search"
    get 'search_tag' => "posts#search_tag"
    get 'search_title' => "posts#search_title"
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only:[:index, :show, :edit, :update] do
      resources :favorites, only: [:index]
      collection do
        get :confirm
        patch :withdrawal
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # 有効なユーザー/退会済みユーザー
  scope :active_users, -> { where(is_status: true) }
  scope :delete_users, -> { where(is_status: false) }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:nick_name]

  # アソシエーション
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  # バリデーション
  validates :nick_name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 150 }
  validates :email, presence: true, uniqueness: true

  # ゲストログインメソッド追加
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64

      user.nick_name = "guestuser"
    end
  end

  # ゲストユーザーの判別メソッド
  def guest_user?
    email == GUEST_USER_EMAIL
  end

  # プロフィール画像追加
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(is_status: false)
      sign_out @user
      flash[:notice] = "強制退会"
      redirect_to admin_user_path(@user)
    else
      render :show
    end
  end

  def active
    @user = User.find(params[:id])
    if @user.update(is_status: true)
      sign_out @user
      flash[:notice] = "有効化"
      redirect_to admin_user_path(@user)
    else
      render :show
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "ゲストユーザーでログインしました"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<!--管理者側ユーザー一覧画面-->
<%= render "admin/shared/user_list", users: @users %>

app/views/admin/users/show.html.erb
<!--管理者側ユーザー詳細画面-->
<div class="container mt-4 mb-4">
  <div class="row">
    <div class="col-md-12">
      <h2>ユーザー詳細</h2>
      <div class="row">
        <div class="col-lg-4">
          <div><%= image_tag @user.get_profile_image(250, 250), class: "w-75" %></div>
        </div>
        <div class="col-lg-5">
          <table class="table">
            <tbody>
              <tr>
                <td>ニックネーム</td>
                <td><%= @user.nick_name %></td>
              </tr>
              <tr>
                <td>投稿数</td>
                <td><%= @user.posts.count %> 件</td>
              </tr>
              <tr>
                <td>コメント数</td>
                <td><%= "#{@user.comments.count}件" %></td>
              </tr>
              <tr>
                <td>
                  <% if @user.is_status == true %>
                    <%= link_to "強制退会", admin_user_path(@user.id), method: :patch, "data-confirm" => "このユーザーを退会させますか？", class: "btn btn-danger ml-4"%>
                  <% else %>
                    <%= link_to "有効化", active_admin_user_path(@user.id), method: :patch, "data-confirm" => "このユーザーを有効にしますか？", class: "btn btn-success ml-4"%>
                  <% end %>
                </td>
                <td><%= link_to "コメント一覧へ", admin_user_comments_path(@user), class: "btn btn-primary" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>