config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ゲストログインルーティング
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :update] do
      resources :comments, only: [:index, :destroy]
      member do
        patch :active
      end
    end
  end

  # ユーザー側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get 'posts/search' => "posts#search"
    get 'search_tag' => "posts#search_tag"
    get 'search_title' => "posts#search_title"
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only:[:index, :show, :edit, :update] do
      resources :favorites, only: [:index]
      collection do
        get :confirm
        patch :withdrawal
      end
    end
  end
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/admin/shared/_user_list.html.erb
<!--管理者側ユーザー一覧部分テンプレート-->
<div class="container mt-3 mb-4">
  <div class="row">
    <div class="col-12">
      <h2>ユーザー一覧</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table class="table">
        <tbody>
          <% users.each do |user| %>
          <tr>
            <td class="align-middle">
              <%= link_to admin_user_path(user) do %>
               <%= image_tag user.get_profile_image(100, 100) %>
              <% end %>
            </td>
            <td class="align-middle"><%= link_to user.nick_name, admin_user_path(user) %></td>
            <td class="align-middle"><%= "投稿数 #{user.posts.count} 件" %></td>
            <td class="align-middle"><%= link_to "コメント #{user.comments.count} 件", admin_user_comments_path(user) %></td>
            <td class="align-middle"><%= user.is_status ? '有効' : '退会' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row flex justify-content-center">
        <%= paginate users, theme: 'twitter-bootstrap-4' %>
      </div>
    </div>
  </div>
</div>