config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ゲストログインルーティング
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :update] do
      resources :comments, only: [:index, :destroy]
      member do
        patch :active
      end
    end
  end

  # ユーザー側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get 'posts/search' => "posts#search"
    get 'search_tag' => "posts#search_tag"
    get 'search_title' => "posts#search_title"
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only:[:index, :show, :edit, :update] do
      resources :favorites, only: [:index]
      collection do
        get :confirm
        patch :withdrawal
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<div class="container mt-5" >
  <div class="row">
    <p class="mx-auto">
      Share your encounters with books
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="z-index:10">
    <a class="m-3 navbar-brand" href="/">
      <i class="fa-solid fa-book-open"></i> 本旅館
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <!--ユーザーログイン後ヘッダー-->
        <% if user_signed_in? %>
          <%= form_with url: search_title_path, local: true, method: :get do |f| %>
            <%= f.text_field :word, placeholder: "Search" %>
          <% end %>
          <li class="nav-item">
            <%= link_to user_path(current_user), class:"nav-link text-light" do %>
              <i class="fa-solid fa-house"></i> マイページ
            <% end %>
          </li>

          <li class="nav-item">
            <%=link_to new_post_path, class:"nav-link text-light" do %>
              <i class="fa-regular fa-square-plus"></i>新規投稿
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to users_path, class:"nav-link text-light" do %>
              <i class="fa-solid fa-users"></i>ユーザー一覧
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
              <i class="fa-solid fa-arrow-right-from-bracket"></i>ログアウト
            <% end %>
          </li>

      <!--管理者側ログイン後ヘッダー-->
        <% elsif admin_signed_in? %>
          <li class="nav-item">
            <%= link_to admin_users_path, class:"nav-link text-light" do %>
              <i class="fa-solid fa-users"></i>ユーザー一覧
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link text-light" do %>
              <i class="fa-solid fa-right-from-bracket"></i> ログアウト
            <% end %>
          </li>

      <!--ログイン前ヘッダー-->
        <% else %>
          <li class="nav-item">
            <%= link_to users_guest_sign_in_path, method: :post, class:"nav-link text-light" do %>
              <i class="fa-regular fa-user"></i> ゲストログイン(閲覧用)
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
              <i class="fa-solid fa-user-plus"></i> サインアップ
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to new_user_session_path, class:"nav-link text-light" do %>
              <i class="fa-solid fa-arrow-right-to-bracket"></i> ログイン
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to about_path , class:"nav-link text-light" do %>
            <i class="fa-solid fa-newspaper"></i> About
            <% end %>
          </li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Honryokan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/713c6e0575.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダー部分テンプレート-->
    <%= render 'layouts/header' %>
    <div class="text-center">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <main>
     <div class="main-container">
      <%= yield %>
     </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>